# gydnc/config.yaml (Revised, Git settings removed)

backends:
  - name: "project_guidance"
    type: "localfs"
    settings:
      rootDir: "../"      # Relative to this config file's location (gydnc/)
                          # Points to the project root.
      guidanceLocations:
        - "guidance/**/*.g6e" # Looks for .g6e files in 'PROJECT_ROOT/guidance/'

  # Example: User-specific guidance
  # - name: "user_guidance"
  #   type: "localfs"
  #   settings:
  #     rootDir: "~/.gydnc_store"
  #     guidanceLocations:
  #       - "**/*.g6e"
